### ISSUE TITLE
Bug Test Alpha

### ISSUE THREAD

**Issue by mythbusterma** [RolecraftDev/RolecraftCore#32]
Before the Alpha release we need to test all the commands, spells, both MySQL and SQLite databases, professions (rules), and mana systems.

**Comment by DziNeIT** [comment]
Fully working as far as known:
Guilds
Guild Chat
Configurable Messages
Events
Spells
Database Storage

Known issues:
Some messages aren't configurable yet

Untested:
Professions
Experience / levelling
Mana
